env:
  node: true
  browser: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'google'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules: {
   require-jsdoc: 0,
   indent: ["error", 2],
}
ecmaFeatures: {
  classes: true
}
